#pragma once

#include "base/macro.h"


#define RENDERING_NAMESPACE_BEGIN				AMAZING_NAMESPACE_BEGIN		\
												NAMESPACE_BEGIN(Rendering)	
#define RENDERING_NAMESPACE_END					NAMESPACE_END(Rendering)		\
												AMAZING_NAMESPACE_END

#define RENDERING_NAMESPACE						NAMESPACE_CONCAT(AMAZING_NAMESPACE, NAMESPACE(Rendering))
#define RENDERING_NAMESPACE_VARIABLE(var)		NAMESPACE_VARIABLE(RENDERING_NAMESPACE, var)