#pragma once

#include "base/macro.h"

#define RENDERING_NAMESPACE_BEGIN				AMAZING_NAMESPACE_BEGIN
#define RENDERING_NAMESPACE_END					AMAZING_NAMESPACE_END
#define RENDERING_NAMESPACE						AMAZING_NAMESPACE
#define RENDERING_NAMESPACE_VARIABLE(var)		NAMESPACE_VARIABLE(RENDERING_NAMESPACE, var)