#pragma once

#include <iostream>
#include <fstream>
#include <vector>
#include <algorithm>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <ranges>
#include <optional>
#include <filesystem>
#include <functional>
#include <array>
#include <queue>
#include <string>
#include <string_view>
#include <format>